export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL';
export const VERIFICATION_SUCCESSFUL = 'VERIFICATION_SUCCESSFUL';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
